version : '3'
services:
  nginx:
    image: nginx:1-alpine
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx
      - ./honeypot-static-content:/var/www/static
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"

  honeypot:
    image: honeypot:1.0
    restart: always
    environment:
      - SECRET_KEY="PUTA"
    ports:
      - 8000:8000
    volumes:
      - ./honeypot-static-content:/app/static-web
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_USER=/run/secrets/db_user
      - POSTGRES_DB=/run/secrets/db_database
    ports:
      - "5432:5432"
    networks:
      - app-network


secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_database:
    file: ./secrets/db_database.txt
networks:
  app-network:
    driver: bridge
