# Generated by Django 5.1.3 on 2024-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpath',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
