# Generated by Django 5.1.3 on 2024-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_urlpath_times_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryname',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credential',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
